# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  blazorProjectPath: '**/ImpactSpace.Core.Blazor.csproj'
  dbMigratorProjectPath: '**/ImpactSpace.Core.DbMigrator.csproj'
  testProjectPath: '**/ImpactSpace.Core.Application.Tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: UseDotNet@2
  displayName: 'Install .NET 7 SDK'
  inputs:
    packageType: 'sdk'
    version: '7.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run integration tests'
  inputs:
    command: 'test'
    projects: '$(testProjectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Blazor app'
  inputs:
    command: 'publish'
    projects: '$(blazorProjectPath)'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/blazor_app'

- task: DotNetCoreCLI@2
  displayName: 'Publish DbMigrator'
  inputs:
    command: 'publish'
    projects: '$(dbMigratorProjectPath)'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/db_migrator'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'