namespace ImpactSpace.Core.Common;

public enum PhoneCountryCode
{
    Australia = 61,
    Brazil = 55,
    Canada = 1,
    China = 86,
    Denmark = 45,
    Finland = 358,
    France = 33,
    Germany = 49,
    India = 91,
    Ireland = 353,
    Italy = 39,
    Japan = 81,
    Mexico = 52,
    Netherlands = 31,
    NewZealand = 64,
    Nigeria = 234,
    Norway = 47,
    Pakistan = 92,
    Philippines = 63,
    Portugal = 351,
    Russia = 7,
    SouthAfrica = 27,
    SouthKorea = 82,
    Spain = 34,
    Sweden = 46,
    Switzerland = 41,
    Turkey = 90,
    UnitedKingdom = 44,
    UnitedStates = 1,
}