# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - 'aspnet-core/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'aspnet-core/**'

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console
    
    - name: Restore dependencies
      run: dotnet restore aspnet-core/ImpactSpace.Core.sln
    
    - name: Build
      run: dotnet build --configuration Release aspnet-core/ImpactSpace.Core.sln
      
    - name: Test Solution with Coverage
      working-directory: aspnet-core
      run: |
        dotnet test --configuration Release --no-build --settings coverage.runsettings --blame --collect:"XPlat Code Coverage" ImpactSpace.Core.sln
        
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Merge Coverage Reports
      run: |
        reportgenerator "-reports:**/coverage.opencover.xml" "-targetdir:./aspnet-core/TestResults/merged" -reporttypes:Cobertura
        ls -la ./aspnet-core/TestResults/merged

    - name: Upload coverage report - Solution Tests
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./aspnet-core/TestResults/merged/Cobertura.xml
        commit: ${{ github.sha }}
        slug: ${{ github.repository }}

