# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - 'aspnet-core/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'aspnet-core/**'

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore aspnet-core/ImpactSpace.Core.sln
    - name: Build
      run: dotnet build --configuration Release aspnet-core/ImpactSpace.Core.sln
    - name: Test Application Layer
      run: dotnet test --configuration Release --verbosity normal aspnet-core/test/ImpactSpace.Core.Application.Tests/ImpactSpace.Core.Application.Tests.csproj
    - name: Test Domain Layer
      run: dotnet test --configuration Release --verbosity normal aspnet-core/test/ImpactSpace.Core.Domain.Tests/ImpactSpace.Core.Domain.Tests.csproj
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
